### ISSUE TITLE
rcurry and similar functions appear to be broken in 3.10.

### ISSUE THREAD

**Issue by SevenSolaris** [Suor/funcy#108]
```>>> has_suffix = rcurry(str.endswith)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\funcy\funcs.py", line 57, in rcurry
    n = get_spec(func).max_n
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\funcy\_inspect.py", line 108, in get_spec
    mod = func.__module__
AttributeError: 'method_descriptor' object has no attribute '__module__'. Did you mean: '__reduce__'?```

**Comment by Suor** [comment]
funcy fails to introspect methods of builtin types.

**Comment by Suor** [comment]
The workaround for now is:
```python
has_suffix = rcurry(str.endswith, 2)
```

**Comment by Suor** [comment]
Also, `str.endswith` actually have 4 params, so your example won't work anyway.

**Comment by Suor** [comment]
Updated docs and readme to recommend specifying `n`. The issue itself is frozen for now, since I don't see much value in doing proper introspection here.

**Comment by Suor** [comment]
Note that as a last resort funcy goes to `inspect.signature()`, which might work or not for the same thing depending on Python version.
