### ISSUE TITLE
Bug in `cache` decorator

### ISSUE THREAD

**Issue by adrian-dankiv** [Suor/funcy#60]
I'm trying to mix positional and keyword arguments:
```
import funcy


@funcy.cache(10)
def func(a, b, c):
    return a + b + c


func(1, b=2, c=3)
```
And I am getting next exception:
```
Traceback (most recent call last):
  File "/home/adr/projects/rogers-qa-analytics/tmp/tmp.py", line 9, in <module>
    func(1, b=2, c=3)
  File "/home/adr/projects/rogers-qa-analytics/.env/lib/python3.6/site-packages/funcy/calc.py", line 121, in wrapper
    result = func(*key, **kwargs)
TypeError: func() got multiple values for argument 'b'
```

It looks like the problem is here:

```
def cache(timeout, key_func=None):
    """Caches a function results for timeout seconds."""
    if isinstance(timeout, int):
        timeout = timedelta(seconds=timeout)

    if key_func is None:
        key_func = lambda *a, **kw: a + tuple(sorted(kw.items())) if kw else a

    def decorator(func):
        cache = {}

        @wraps(func)
        def wrapper(*args, **kwargs):
            key = key_func(*args, **kwargs)
            if key in cache:
                result, timestamp = cache[key]
                if datetime.now() - timestamp < timeout:
                    return result
                else:
                    del cache[key]

            result = func(*key, **kwargs)  # <-- here should be *args instead of *key
            cache[key] = result, datetime.now()
            return result

        def invalidate(*args, **kwargs):
            cache.pop(key_func(*args, **kwargs))
        wrapper.invalidate = invalidate

        def invalidate_all():
            cache.clear()
        wrapper.invalidate_all = invalidate_all

        return wrapper
    return decorator
```

**Comment by Suor** [comment]
Good catch.
